image: mcr.microsoft.com/dotnet/core/sdk:3.1

before_script:
    - "dotnet --info"

stages:
    - build
    - test

build:
    stage: build
    script:
        - "dotnet build"
    artifacts:
      paths:
        - bin/

test:
    stage: test
    script: 
        - "dotnet test"